font_family JetBrains Mono
close_on_child_death yes
cursor_trail 200
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

shell fish

# BEGIN_KITTY_THEME
# Carbonfox
include current-theme.conf
# END_KITTY_THEME
